blueprint:
  name: Notificações Personalizadas de Tarefas e Eventos
  domain: automation
  description: Envia notificações com tarefas e eventos do dia em um horário específico.

variables:
  calendars:
    description: Lista de entidades de calendário
  todo_list:
    description: Entidade do todo.item_list
  notification_time:
    description: Horário para enviar a notificação (formato: HH:MM)

trigger:
  - platform: time
    at: '{{ states.input_text.notification_time.state }}'

action:
  - service: notify.mobile_app_your_phone
    data:
      message: >-
        **Tarefas para hoje:**
        {% for item in states.todo.todo_list.attributes.items %}
        - {{ item.name }} (vencimento: {{ item.due_date }})
        {% endfor %}

        **Eventos do dia:**
        {% for calendar in variables.calendars %}
        {% for event in states.calendar.{{ calendar }}.attributes.events %}
        - {{ event.summary }} ({{ event.start.dateTime }})
        {% endfor %}
        {% endfor %}
