blueprint:
  name: Anunciar na Alexa
  description: Faz um anúncio nas caixas Echo selecionadas com volume ajustável.
  domain: script
mode: queued
fields:
  mensagem:
    selector:
      text: null
    name: Mensagem
    description: O que você deseja anunciar?
    required: true
  onde_anunciar:
    selector:
      entity:
        filter:
          - integration: alexa_media
            domain: media_player
        multiple: true
    name: Onde Anunciar
    required: true
    description: Selecione os dispositivos Alexa para o anúncio.
  volume:
    selector:
      number:
        min: 0.1
        max: 1
        step: 0.1
    default: 0.6
    name: Volume do Anúncio
    description: Defina o volume do anúncio (padrão 60%).
sequence:
  - service: media_player.volume_set
    data:
      volume_level: "{{ volume }}"
    target:
      entity_id: "{{ onde_anunciar }}"
  - delay:
      seconds: 1
  - service: notify.alexa_media
    data:
      message: "{{ mensagem }}"
      data:
        type: announce
      target: "{{ onde_anunciar }}"
  - delay:
      seconds: 10
  - service: media_player.volume_set
    data:
      volume_level: 0.3
    target:
      entity_id: "{{ onde_anunciar }}"
icon: mdi:bullhorn