blueprint:
  name: Lembrete de Remédio em Horários Definidos
  description: "Cria lembretes de remédios com horários definidos a partir de uma lista."
  domain: automation
  input:
    notify_service:
      name: Serviço de notificação
      description: "Serviço de notificação para enviar o lembrete."
      default: "notify.mqtt_notify"
      selector:
        text: {}

    lembretes:
      name: Lembretes
      description: >
        Adicione os lembretes no formato:
        nome_remedio_1, HH:MM, descricao_remedio_1
        nome_remedio_2, HH:MM, descricao_remedio_2
      selector:
        text:
          multiline: true

trigger:
  - platform: time
    at: >
      {% set lembretes_raw = (state_attr('automation.lembrete_de_remedio_em_horarios_definidos', 'lembretes') or '') %}
      {% set lembretes_lines = lembretes_raw.split('\n') %}
      {% for line in lembretes_lines %}
        {% set parts = line.split(',') %}
        {% if parts | length == 3 %}
          {% set horario_remedio = parts[1].strip() %}
          {{ horario_remedio }}
        {% endif %}
      {% endfor %}
      {{ '' }}  # Se não houver lembretes, não define nenhum horário

action:
  - variables:
      lembretes_raw: !input lembretes
      lembretes_lines: "{{ lembretes_raw.split('\n') }}"
      reminder_list: >
        {% set lembretes = [] %}
        {% for line in lembretes_lines %}
          {% set parts = line.split(',') %}
          {% if parts | length == 3 %}
            {% set lembrete = {
              "nome_remedio": parts[0].strip(),
              "horario_remedio": parts[1].strip(),
              "descricao_remedio": parts[2].strip()
            } %}
            {% set lembretes = lembretes + [lembrete] %}
          {% endif %}
        {% endfor %}
        {{ lembretes }}

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set current_time = now().strftime('%H:%M') %}
              {% for lembrete in reminder_list %}
                {% if lembrete.horario_remedio == current_time %}
                  true
                {% endif %}
              {% endfor %}
              false
        sequence:
          - repeat:
              count: "{{ reminder_list | length }}"
              sequence:
                - variables:
                    reminder: "{{ reminder_list[repeat.index] }}"
                - service: "{{ notify_service }}"
                  data:
                    message: >
                      Lembrete de remédio: 
                      - Nome: {{ reminder.nome_remedio }}
                      - Horário: {{ reminder.horario_remedio }}
                      - Descrição: {{ reminder.descricao_remedio }}
