blueprint:
  name: Lembrete de Remédio Dinâmico
  description: "Cria lembretes de remédios de maneira flexível, permitindo adicionar e remover quantos lembretes desejar."
  domain: automation
  input:
    notify_service:
      name: Serviço de notificação
      description: "Serviço de notificação para enviar o lembrete."
      default: "notify.mqtt_notify"
      selector:
        text: {}

    lembretes:
      name: Lembretes de Remédio
      description: "Adicione quantos lembretes de remédio quiser, com nome, horário e descrição."
      selector:
        object:
          multiple: true
          label:
            nome_remedio:
              name: Nome do Remédio
              selector:
                text: {}

            horario_remedio:
              name: Horário do Lembrete
              selector:
                time: {}

            descricao_remedio:
              name: Descrição do Remédio
              selector:
                text: {}

variables:
  reminders: !input lembretes

trigger:
  # Gera um trigger para cada lembrete baseado no horário
  - platform: template
    value_template: "{{ (reminders | map(attribute='horario_remedio') | list) | join(', ') }}"

condition: []

action:
  - repeat:
      count: "{{ reminders | length }}"
      sequence:
        - variables:
            reminder: "{{ reminders[repeat.index] }}"
        - choose:
            - conditions: "{{ now().strftime('%H:%M') == reminder.horario_remedio }}"
              sequence:
                - service: !input notify_service
                  data:
                    message: >
                      Lembrete de remédio: 
                      - Nome: {{ reminder.nome_remedio }}
                      - Horário: {{ reminder.horario_remedio }}
                      - Descrição: {{ reminder.descricao_remedio }}
