blueprint:
  name: Lembrete Remédio
  description: Cria lembretes de remédio em determinados horários.
  domain: automation
  input:
    notification_target:
      name: Serviço de Notificação
      description: Serviço de notificação que irá enviar a mensagem.
      default: "notify.mqtt_notify"
      selector:
        text:
    remedio_lista:
      name: Lista de Remédios
      description: Insira os remédios no formato --- Nome, Horário, Descrição
      selector:
        text:
          multiline: true

variables:
  remedio_lista: !input remedio_lista

triggers:
  - trigger: time_pattern
    minutes: /1

condition:
  - condition: template
    value_template: >
      {% set remedios = remedio_lista.split('\n') %}
      {% set horarios = [] %}
      {% for remedio in remedios %}
        {% set remedio_dados = remedio.split(',') %}
        {% if remedio_dados | length > 1 %}
          {% if remedio_dados[1].strip() == now().strftime('%H:%M') %}
            {% set horarios = horarios + [remedio_dados] %}
          {% endif %}
        {% endif %}
      {% endfor %}
      {{ horarios | length > 0 }}

action:
  - alias: Preparar texto da notificação
    data:
      text: >-
        Lista de Remédios para Agora:
        
        {%- set remedios = remedio_lista.split('\n') | selectattr(1, 'equalto', now().strftime('%H:%M')) | list -%}
        {%- for remedio in remedios -%}
          - **Remédio**: {{ remedio.split(',')[0].strip() }} 💊
            **Horário**: {{ remedio.split(',')[1].strip() }} ⏰
            **Instrução**: {{ remedio.split(',')[2].strip() }}
        {%- endfor -%}

      agent_id: conversation.google_generative_ai
    response_variable: agent
    action: conversation.process

  - alias: Enviar notificação
    service: !input notification_target
    data:
      title: "{{ now().strftime('%A') }} Lembrete de Remédios"
      message: "{{ agent.response.speech.plain.speech }}"