blueprint:
  name: Execução Sequencial de Scripts com MQTT e Notificações
  description: Executa scripts via MQTT em ordem, notifica e verifica o status dos scripts, com opções para executar automações ou scripts do Home Assistant antes de publicar no tópico MQTT.
  domain: automation
  input:
    notify_target:
      name: Notificação
      description: Entidade de notificação para enviar as mensagens
      selector:
        entity:
          domain: notify
      default: notify.mqtt_notify
    status_topic:
      name: Tópico de Status
      description: Tópico MQTT para verificar o status dos scripts
      default: home/script/status
    script_topic:
      name: Tópico de Scripts
      description: Tópico MQTT para publicar o nome dos scripts
      default: home/script
    pre_execution_actions:
      name: Ações Antes da Execução
      description: Automação ou scripts do Home Assistant para executar antes da publicação no tópico MQTT
      default: []
      selector:
        action:
    script_name_1:
      name: Nome do Script 1
      description: Nome do primeiro script para publicar no tópico MQTT
      default: ""
      selector:
        text: {}
    script_name_2:
      name: Nome do Script 2
      description: Nome do segundo script para publicar no tópico MQTT
      default: ""
      selector:
        text: {}
    script_name_3:
      name: Nome do Script 3
      description: Nome do terceiro script para publicar no tópico MQTT
      default: ""
      selector:
        text: {}
    script_name_4:
      name: Nome do Script 4
      description: Nome do quarto script para publicar no tópico MQTT
      default: ""
      selector:
        text: {}
    script_name_5:
      name: Nome do Script 5
      description: Nome do quinto script para publicar no tópico MQTT
      default: ""
      selector:
        text: {}
    # Adicione mais campos conforme necessário

trigger:
  - platform: homeassistant
    event: start

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ pre_execution_actions | length > 0 }}"
        sequence:
          - service: homeassistant.trigger
            target:
              entity_id: !input pre_execution_actions

  - variables:
      # Construir a lista de scripts a partir das entradas
      script_list: >
        {% set names = [
          (input.script_name_1 | default('')).strip(),
          (input.script_name_2 | default('')).strip(),
          (input.script_name_3 | default('')).strip(),
          (input.script_name_4 | default('')).strip(),
          (input.script_name_5 | default('')).strip()
          # Adicione mais entradas conforme necessário
        ] %}
        {{ names | select('!=', '') | list }}

  - repeat:
      count: "{{ script_list | length }}"
      sequence:
        - service: mqtt.publish
          data:
            topic: !input script_topic
            payload: "{{ script_list[repeat.index] }}"
          
        - wait_for_trigger:
            - platform: mqtt
              topic: !input status_topic
              payload: "{{ script_list[repeat.index] }}: Sucesso"
            - platform: mqtt
              topic: !input status_topic
              payload: "{{ script_list[repeat.index] }}: Falhou"
          
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ trigger.payload == (script_list[repeat.index] + ': Sucesso') }}"
              sequence:
                - service: notify.notify_target
                  data:
                    message: "O script {{ script_list[repeat.index] }} foi executado com sucesso."
            - conditions:
                - condition: template
                  value_template: "{{ trigger.payload == (script_list[repeat.index] + ': Falhou') }}"
              sequence:
                - service: notify.notify_target
                  data:
                    message: "Falha ao executar o script {{ script_list[repeat.index] }}."
