blueprint:
  name: Execução Sequencial de Scripts com MQTT e Notificações
  description: Executa scripts via MQTT em ordem, notifica e verifica o status dos scripts, com opções para executar automações ou scripts do Home Assistant antes de publicar no tópico MQTT.
  domain: automation
  input:
    notify_target:
      name: Notificação
      description: Entidade de notificação para enviar as mensagens
      selector:
        entity:
          domain: notify
      default: notify.mqtt_notify
    status_topic:
      name: Tópico de Status
      description: Tópico MQTT para verificar o status dos scripts
      default: home/script/status
    script_topic:
      name: Tópico de Scripts
      description: Tópico MQTT para publicar o nome dos scripts
      default: home/script
    pre_execution_actions:
      name: Ações Antes da Execução
      description: Automação ou scripts do Home Assistant para executar antes da publicação no tópico MQTT
      default: []
      selector:
        action:
    script_names:
      name: Nomes dos Scripts
      description: Nomes dos scripts para publicar no tópico MQTT em ordem de execução, separados por vírgula
      default: ""
      selector:
        text:
        
trigger:
  - platform: homeassistant
    event: start

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ pre_execution_actions | length > 0 }}"
        sequence:
          - service: homeassistant.trigger
            target:
              entity_id: !input pre_execution_actions

  - variables:
      script_list: "{{ script_names.split(',') | map('trim') | list }}"

  - repeat:
      count: "{{ script_list | length }}"
      sequence:
        - service: mqtt.publish
          data:
            topic: !input script_topic
            payload: "{{ script_list[repeat.index] }}"
          
        - wait_for_trigger:
            - platform: mqtt
              topic: !input status_topic
              payload: "{{ script_list[repeat.index] }}: Sucesso"
            - platform: mqtt
              topic: !input status_topic
              payload: "{{ script_list[repeat.index] }}: Falhou"
          
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ trigger.payload == (script_list[repeat.index] + ': Sucesso') }}"
              sequence:
                - service: notify.notify_target
                  data:
                    message: "O script {{ script_list[repeat.index] }} foi executado com sucesso."
            - conditions:
                - condition: template
                  value_template: "{{ trigger.payload == (script_list[repeat.index] + ': Falhou') }}"
              sequence:
                - service: notify.notify_target
                  data:
                    message: "Falha ao executar o script {{ script_list[repeat.index] }}."
