blueprint:
  name: Notificação Personalizada com IA Generativa
  description: Gera uma mensagem personalizada com IA generativa e envia por um serviço de notificação.
  domain: script
mode: queued
fields:
  mensagem:
    selector:
      text: null
    name: Mensagem
    description: Texto que será utilizado como base para gerar a mensagem personalizada.
    required: true
  notification_target:
    name: Serviço de Notificação
    description: Serviço de notificação que irá enviar a mensagem.
    default: "notify.mqtt_notify"
    selector:
      text:
  telegram_chat_id: 
    name: ID do Chat do Telegram
    description: O ID numérico do chat do Telegram para onde a mensagem será enviada. Pode ser de um usuário ou grupo.
    default: "29832395"
    selector:
      text::
  prompt:
    name: Prompt
    description: Prompt do generative ai conversation.
    selector:
      text:
        multiline: true
    default: >-
      Você é a FRIDAY do Homem de Ferro, e uma assistente pessoal da minha casa.
sequence:
  - service: google_generative_ai_conversation.generate_content
    data:
      prompt: >-
        {{ prompt | default('') }}

        O nome do seu mestre e pai é Ruan, mas me chame de Mestre apenas.
        Você atua como assistente pessoal da casa.
        Crie mensagens variando o estilo a cada vez.
        Não diga para quem é a mensagem (Telegram ou Alexa), apenas gere o conteúdo.
        Não envie "\n" e nem tente fazer quebras de linha assim, pois não funciona no Telegram.
        Gere uma mensagem única, criativa e personalizada para informar que: "{{ mensagem }}"
    response_variable: mensagem_personalizada
  - delay:
      seconds: 1
  - service: "{{ notification_target }}"
    data:
      message: "{{ mensagem_personalizada['text'] | replace('\n', ' ') }}"
      data: 
        chat_id: "{{ telegram_chat_id }}" 
icon: mdi:message
